<h1>Bienvenue dans ce blog</h1>


<section class="articles">
    
     <div class="article">
      <div class="left">
        <img src="https://cdn.pixabay.com/photo/2016/11/18/19/01/paris-1836415_1280.jpg" alt="">
      </div>
      <div class="right">
        <p class="date">Juillet, 24, 2020</p>
        <h1>Paris - La ville des lumières, pourquoi ?</h1>
        <p class="description">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad cupiditate repellendus dolor necessitatibus. Modi, quos! Explicabo voluptates vero ullam quis ipsum impedit illum numquam cum quaerat animi? Ad, fugiat neque.</p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div> 
    
    
    <div class="article">
      <div class="left">
        <img src="https://cdn.pixabay.com/photo/2016/01/19/17/15/night-1149601_1280.jpg" alt="">
      </div>
      <div class="right">
        <p class="date">Juillet, 24, 2020</p>
        <h1>Interview - Une ville nocture est elle si belle ?</h1>
        <p class="description">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad cupiditate repellendus dolor necessitatibus. Modi, quos! Explicabo voluptates vero ullam quis ipsum impedit illum numquam cum quaerat animi? Ad, fugiat neque.</p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div>
    
    <div class="article">
      <div class="left">
        <img src="https://cdn.pixabay.com/photo/2017/01/09/16/15/calanque-1966920_1280.jpg" alt="">
      </div>
      <div class="right">
        <p class="date">Juillet, 24, 2020</p>
        <h1>Les calanques, une belle destination touristique</h1>
        <p class="description">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad cupiditate repellendus dolor necessitatibus. Modi, quos! Explicabo voluptates vero ullam quis ipsum impedit illum numquam cum quaerat animi? Ad, fugiat neque.</p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div>
  </section>
  
  
</body>
</html>
<style>

.articles{
  margin-top: 30px;
}
.articles .article{
  display: flex;
  flex-wrap:wrap;
  margin-bottom: 30px;
}
.articles .article .left img{
  height: 300px;
  width: 500px;
}
.articles .article .right {
  margin-left: 40px;
  max-width: 50%;
}
.articles .article .right p.date{
  color: #7f7e7e;
}
.articles .article .right p.description{
  color: #2d2d2d;
}
</style>